services:
  app:
    build: .
    ports:
      - "5252:5252"
    environment:
      MONGO_URI: mongodb://mongo-db:27017/
      MONGO_DB_NAME: "vaultody"
      MAX_POOL_SIZE: 10
      PORT: 5252
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
